export const MANUFACTURERS = [
  { id: 'apple', label: '애플' },
  { id: 'samsung', label: '삼성' },
];

export type Model = {
  id: string;
  label: string;
  brand: 'apple' | 'samsung';
  hasSeries?: boolean;
};

export const MODELS: Model[] = [
  // 갤럭시 S 시리즈
  { id: 'galaxy-s6', label: '갤럭시 S6', brand: 'samsung' },
  { id: 'galaxy-s7', label: '갤럭시 S7', brand: 'samsung' },
  { id: 'galaxy-s8', label: '갤럭시 S8', brand: 'samsung' },
  { id: 'galaxy-s9', label: '갤럭시 S9', brand: 'samsung' },
  { id: 'galaxy-s10', label: '갤럭시 S10', brand: 'samsung' },
  { id: 'galaxy-s20', label: '갤럭시 S20', brand: 'samsung', hasSeries: true },
  { id: 'galaxy-s21', label: '갤럭시 S21', brand: 'samsung', hasSeries: true },
  { id: 'galaxy-s22', label: '갤럭시 S22', brand: 'samsung', hasSeries: true },
  { id: 'galaxy-s23', label: '갤럭시 S23', brand: 'samsung', hasSeries: true },
  { id: 'galaxy-s24', label: '갤럭시 S24', brand: 'samsung', hasSeries: true },
  { id: 'galaxy-s25', label: '갤럭시 S25', brand: 'samsung', hasSeries: true },
  // 갤럭시 Z 폴드
  { id: 'galaxy-z-fold', label: '갤럭시 Z 폴드', brand: 'samsung' },
  { id: 'galaxy-z-fold2', label: '갤럭시 Z 폴드2', brand: 'samsung' },
  { id: 'galaxy-z-fold3', label: '갤럭시 Z 폴드3', brand: 'samsung' },
  { id: 'galaxy-z-fold4', label: '갤럭시 Z 폴드4', brand: 'samsung' },
  { id: 'galaxy-z-fold5', label: '갤럭시 Z 폴드5', brand: 'samsung' },
  { id: 'galaxy-z-fold6', label: '갤럭시 Z 폴드6', brand: 'samsung' },
  { id: 'galaxy-z-fold-se', label: '갤럭시 Z 폴드 SE', brand: 'samsung' },
  { id: 'galaxy-z-fold7', label: '갤럭시 Z 폴드7', brand: 'samsung' },
  // 갤럭시 Z 플립
  { id: 'galaxy-z-flip', label: '갤럭시 Z 플립', brand: 'samsung' },
  { id: 'galaxy-z-flip2', label: '갤럭시 Z 플립2', brand: 'samsung' },
  { id: 'galaxy-z-flip3', label: '갤럭시 Z 플립3', brand: 'samsung' },
  { id: 'galaxy-z-flip4', label: '갤럭시 Z 플립4', brand: 'samsung' },
  { id: 'galaxy-z-flip5', label: '갤럭시 Z 플립5', brand: 'samsung' },
  { id: 'galaxy-z-flip6', label: '갤럭시 Z 플립6', brand: 'samsung' },
  { id: 'galaxy-z-flip7', label: '갤럭시 Z 플립7', brand: 'samsung' },
  { id: 'galaxy-z-trifold', label: '갤럭시 Z 트라이플드', brand: 'samsung' },
  // 아이폰
  { id: 'iphone-5', label: '아이폰 5', brand: 'apple' },
  { id: 'iphone-6', label: '아이폰 6', brand: 'apple' },
  { id: 'iphone-7', label: '아이폰 7', brand: 'apple' },
  { id: 'iphone-8', label: '아이폰 8', brand: 'apple' },
  { id: 'iphone-x', label: '아이폰 X', brand: 'apple' },
  { id: 'iphone-xr', label: '아이폰 XR', brand: 'apple' },
  { id: 'iphone-xs', label: '아이폰 XS', brand: 'apple' },
  { id: 'iphone-11', label: '아이폰 11', brand: 'apple', hasSeries: true },
  { id: 'iphone-12', label: '아이폰 12', brand: 'apple', hasSeries: true },
  { id: 'iphone-13', label: '아이폰 13', brand: 'apple', hasSeries: true },
  { id: 'iphone-14', label: '아이폰 14', brand: 'apple', hasSeries: true },
  { id: 'iphone-15', label: '아이폰 15', brand: 'apple', hasSeries: true },
  { id: 'iphone-16', label: '아이폰 16', brand: 'apple', hasSeries: true },
  { id: 'iphone-17', label: '아이폰 17', brand: 'apple', hasSeries: true },
  { id: 'iphone-se', label: '아이폰 SE', brand: 'apple' },
  { id: 'iphone-se-2', label: '아이폰 SE 2세대', brand: 'apple' },
  { id: 'iphone-se-3', label: '아이폰 SE 3세대', brand: 'apple' },
  // 아이패드
  { id: 'ipad-1', label: '아이패드 1', brand: 'apple' },
  { id: 'ipad-2', label: '아이패드 2', brand: 'apple' },
  { id: 'ipad-3', label: '아이패드 3세대', brand: 'apple' },
  { id: 'ipad-4', label: '아이패드 4세대', brand: 'apple' },
  { id: 'ipad-5', label: '아이패드 5세대', brand: 'apple' },
  { id: 'ipad-6', label: '아이패드 6세대', brand: 'apple' },
  { id: 'ipad-7', label: '아이패드 7세대', brand: 'apple' },
  { id: 'ipad-8', label: '아이패드 8세대', brand: 'apple' },
  { id: 'ipad-9', label: '아이패드 9세대', brand: 'apple' },
  { id: 'ipad-10', label: '아이패드 10세대', brand: 'apple' },
  { id: 'ipad-a16', label: '아이패드 A16', brand: 'apple' },
  // 아이패드 mini
  { id: 'ipad-mini', label: '아이패드 mini', brand: 'apple' },
  { id: 'ipad-mini2', label: '아이패드 mini2', brand: 'apple' },
  { id: 'ipad-mini3', label: '아이패드 mini3', brand: 'apple' },
  { id: 'ipad-mini4', label: '아이패드 mini4', brand: 'apple' },
  { id: 'ipad-mini-5', label: '아이패드 mini 5세대', brand: 'apple' },
  { id: 'ipad-mini-6', label: '아이패드 mini 6세대', brand: 'apple' },
  { id: 'ipad-mini-a17-pro', label: '아이패드 mini A17 Pro', brand: 'apple' },
  // 아이패드 Air
  { id: 'ipad-air', label: '아이패드 Air', brand: 'apple' },
  { id: 'ipad-air2', label: '아이패드 Air2', brand: 'apple' },
  { id: 'ipad-air-3', label: '아이패드 Air 3세대', brand: 'apple' },
  { id: 'ipad-air-4', label: '아이패드 Air 4세대', brand: 'apple' },
  { id: 'ipad-air-5', label: '아이패드 Air 5세대', brand: 'apple' },
  { id: 'ipad-air-11-m2', label: '아이패드 Air 11 (M2)', brand: 'apple' },
  { id: 'ipad-air-13-m2', label: '아이패드 Air 13 (M2)', brand: 'apple' },
  { id: 'ipad-air-11-m3', label: '아이패드 Air 11 (M3)', brand: 'apple' },
  { id: 'ipad-air-13-m3', label: '아이패드 Air 13 (M3)', brand: 'apple' },
  // 아이패드 Pro
  { id: 'ipad-pro-9.7', label: '아이패드 Pro 9.7', brand: 'apple' },
  { id: 'ipad-pro-10.5', label: '아이패드 Pro 10.5', brand: 'apple' },
  { id: 'ipad-pro-11', label: '아이패드 Pro 11', brand: 'apple' },
  { id: 'ipad-pro-11-2', label: '아이패드 Pro 11 2세대', brand: 'apple' },
  { id: 'ipad-pro-11-3', label: '아이패드 Pro 11 3세대', brand: 'apple' },
  { id: 'ipad-pro-11-4', label: '아이패드 Pro 11 4세대', brand: 'apple' },
  { id: 'ipad-pro-12.9', label: '아이패드 Pro 12.9', brand: 'apple' },
  { id: 'ipad-pro-12.9-2', label: '아이패드 Pro 12.9 2세대', brand: 'apple' },
  { id: 'ipad-pro-12.9-3', label: '아이패드 Pro 12.9 3세대', brand: 'apple' },
  { id: 'ipad-pro-12.9-4', label: '아이패드 Pro 12.9 4세대', brand: 'apple' },
  { id: 'ipad-pro-12.9-5', label: '아이패드 Pro 12.9 5세대', brand: 'apple' },
  { id: 'ipad-pro-12.9-6', label: '아이패드 Pro 12.9 6세대', brand: 'apple' },
  { id: 'ipad-pro-13', label: '아이패드 Pro 13', brand: 'apple' },
  // 애플워치
  { id: 'apple-watch-1', label: '애플워치 1', brand: 'apple' },
  { id: 'apple-watch-2', label: '애플워치 2', brand: 'apple' },
  { id: 'apple-watch-3', label: '애플워치 3', brand: 'apple' },
  { id: 'apple-watch-4', label: '애플워치 4', brand: 'apple' },
  { id: 'apple-watch-5', label: '애플워치 5', brand: 'apple' },
  { id: 'apple-watch-6', label: '애플워치 6', brand: 'apple' },
  { id: 'apple-watch-7', label: '애플워치 7', brand: 'apple' },
  { id: 'apple-watch-8', label: '애플워치 8', brand: 'apple' },
  { id: 'apple-watch-9', label: '애플워치 9', brand: 'apple' },
  { id: 'apple-watch-10', label: '애플워치 10', brand: 'apple' },
  { id: 'apple-watch-11', label: '애플워치 11', brand: 'apple' },
  { id: 'apple-watch-se', label: '애플워치 SE', brand: 'apple' },
  { id: 'apple-watch-se-2', label: '애플워치 SE 2', brand: 'apple' },
  { id: 'apple-watch-se-3', label: '애플워치 SE 3', brand: 'apple' },
  { id: 'apple-watch-ultra', label: '애플워치 Ultra', brand: 'apple' },
  { id: 'apple-watch-ultra-2', label: '애플워치 Ultra 2', brand: 'apple' },
];

export const PRICE_RANGES = [
  { id: 'under-10', label: '10만원이하', min: 0, max: 100000 },
  { id: '10-30', label: '10만원~30만원대', min: 100000, max: 400000 },
  { id: '30-60', label: '30만원~60만원대', min: 400000, max: 700000 },
  { id: '60-90', label: '60만원~90만원대', min: 700000, max: 1000000 },
  { id: '100+', label: '100만원대이상', min: 1000000, max: Infinity },
];
