import { tv } from 'tailwind-variants';

export const cardVariants = tv({
  slots: {
    root: [
      'group',
      'flex',
      'flex-col',
      'items-center',
      'w-[282px]',
      'h-[399px]',
      'gap-[14px]',
      'bg-white',
      'cursor-pointer',
      'shrink-0',
    ],
    imageWrapper: [
      'relative',
      'flex',
      'py-[10px]',
      'px-[var(--padding-s)]',
      'items-start',
      'gap-[10px]',
      'flex-[1_0_0]',
      'self-stretch',
      'rounded-[var(--radius-l)]',
      'bg-gray-300',
      'overflow-hidden',
    ],
    image: ['absolute', 'inset-0', 'w-full', 'h-full', 'object-cover', 'rounded-[var(--radius-l)]'],
    overlay: [
      'absolute',
      'inset-0',
      'rounded-[var(--radius-l)]',
      'bg-white/20',
      'opacity-0',
      'transition-opacity',
      'pointer-events-none',
      'group-hover:opacity-100',
    ],
    title: [
      'h-[48px]',
      'self-stretch',
      'overflow-hidden',
      'text-ellipsis',
      'whitespace-nowrap',
      'typo-body-1',
      'text-gray-900',
    ],
    price: ['self-stretch', 'typo-body-2', 'font-semibold', 'text-gray-900'],
    date: ['self-stretch', 'typo-caption-2', 'font-normal', 'text-gray-500'],
    textWrapper: ['flex', 'flex-col', 'items-start', 'gap-1', 'self-stretch', 'px-[var(--padding-s)]'],
  },
});
